apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169944864
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169944864
    app.kubernetes.io/part-of: test-app-169944864
  name: java-quarkus-169944864
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169944864
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169944864
    spec:
      containers:
      - image: quay.io/hacdev/mfbuvzjj-tenant/test-app-169944864/java-quarkus-169944864@sha256:c0e82daeec358c6d15ff3c454716f76288bd20293dddb9a224d0eb5088456cff
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
